## Copyright (c) 2020 mangalbhaskar
"""This provides the standardized way providing the timestamp,
dates and some other parameters."""
__author__ = 'mangalbhaskar'


__all__ = [
  '_date_format_'
  ,'_timestamp_format_'
  ,'_banner_'
  ,'_shebang_'
  ,'_copyright_'
]

_date_format_ = 'YYYY-MM-DD HH:mm:ss ZZ'
_timestamp_format_ = "{:%d%m%y_%H%M%S}"

_banner_="This file is autogenerated and will be overwritten!"
_shebang_="#!/bin/bash"
_copyright_="Copyright (c) 2020 mangalbhaskar"
